-- name: selectTimelineList
SELECT
    TOPIC_UID,
    TOPIC_NAME,
    REGISTRATION_DATE,
    REGISTRATION_USER,
    FLAG_DELETED
FROM
    TOPIC
WHERE
    FLAG_DELETED = 'N'
ORDER BY
    REGISTRATION_DATE DESC;