-- name: selectTopicList
SELECT
    TOPIC_UID       AS topic_uid
	, TOPIC_NAME    AS topic_name
	, CASE 
		WHEN 
            REGISTRATION_USER = 'USR-4a7ac19358e446ca8a389a36299b80ec'
		THEN 
            TRUE
		ELSE 
            FALSE
	END	            AS is_mine
FROM
    TOPIC
WHERE
    FLAG_DELETED = 'N'
ORDER BY
    REGISTRATION_DATE DESC;

-- name: selectDateList
SELECT
	  DATE
	, MAX(COUNT_PER_TOPIC) AS DATE_SLOT_COUNT
FROM (
	SELECT
		  DATE
		, TOPIC_UID
		, COUNT(*) AS COUNT_PER_TOPIC
	FROM
		NEWS
	GROUP BY
		  DATE
		, TOPIC_UID
) AS SUB
GROUP BY
	DATE
ORDER BY
	DATE ASC;

-- name: selectNewsList
SELECT 
	NEWS_UID
	, TOPIC_UID
	, TITLE
	, DATE
	, MEMO
    , IMPORTANCE
FROM 
	NEWS
WHERE
	FLAG_DELETED = 'N'
ORDER BY
	DATE ASC, TOPIC_UID ASC, REGISTRATION_DATE ASC;